title: Asad Shamna Blogs
description: "A one-stop hacking tips and tricks"
author:
  name: "Asad Shamna"
  email: "business.asad.shamna@gmail.com"
  url: "https://asadshamna.github.io"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page/:num/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner: "Asad Shamna"
year: "2026"

nav:
  - name: Home
    link: /
  - name: Tutorials
    link: /tutorials/
  - name: Writeups
    link: /writeups/
  - name: About
    link: /about/
